server:
  port: 8060

logging:
  config: classpath:logs/logback-spring.xml
  file: logs/nc_log_all.log
  pattern: file=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
  level:
    com:
      longshine:
        guangdong:
          mapper: debug
file:
  path:
    linux: /home/output
    ncmllin: /home/ncmltemp
request:
  param:
    uri: http://172.22.1.175/di/http.action
    userId: idc
    pwd: U3cuYV
    interfaceId: getSurfAwstQC4Iiiii
    dataFormat: json

