# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  servlet:
    context-path: /dynamic

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB   # 最大支持文件大小
      max-request-size: 100MB  # 最大支持请求大小
      enabled: true     #默认支持文件上传.

#mybatis config
mybatis:
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package:
  mapper-locations:  classpath*:mapper/**/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl